
name: Cypress Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
  #maquina que será executada
    runs-on: ubuntu-latest

    steps:
    #clone do projeto
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
               with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}