name: Cypress Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    # Máquina que será executada
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala as dependências
      - name: Install dependencies
        run: npm ci

      # Executa os testes do Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}